# Generated by Django 3.2.12 on 2023-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
                ('age', models.IntegerField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('contact', models.IntegerField(max_length=45)),
                ('amount', models.IntegerField(max_length=45)),
            ],
        ),
    ]
