# Generated by Django 3.2.12 on 2023-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='amount',
            field=models.IntegerField(max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
