# Generated by Django 3.2.12 on 2023-03-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethcrud', '0002_auto_20230322_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField(max_length=13)),
                ('amount', models.IntegerField(max_length=10000000000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
